/* Copyright (c) 2026 Richard Rodger, MIT License */

// Cross-runtime drift gates for the machine-readable contract files in
// ../schema (pattern precedent: version_test.go reads ../ts/package.json).
//
// - grammar.schema.json: the schema's alt property names must equal the
//   keys the Go GrammarAltSpec declares. ts/test/schema.test.js asserts
//   the same names against the TS runtime's accepted keys, so the two
//   runtimes cannot silently diverge on the serialized-alt surface.
//
// - error-codes.json: generated from the TS merged catalogues
//   (ts/tools/gen-error-codes.js). Checked in BOTH directions here:
//   every registry entry must match Go's merged catalogue byte-for-byte,
//   and every Go catalogue entry must appear in the registry (base codes
//   under "codes", the Go-only `internal` under "goOnly"). Only the CODES
//   are contractual across runtimes (AGENTS.md "Error codes"); the
//   registry pins the templates anyway so drift is deliberate, not
//   accidental.
//
// Nothing here is skipped on error: a drift gate that silently does not
// run is the failure mode these tests exist to prevent.

package tabnas

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
)

// goAltKeys derives the serialized alt keys from the GrammarAltSpec struct
// (go/grammarspec.go): the json tag when one is declared, else the
// lowercased field name — which is exactly the map key mapToGrammarAltSpec
// reads for each field (the struct has no json tags today because
// GrammarSpecFromJSON decodes via plain maps, not struct unmarshalling).
func goAltKeys(t *testing.T) []string {
	t.Helper()
	typ := reflect.TypeOf(GrammarAltSpec{})
	keys := make([]string, 0, typ.NumField())
	for i := 0; i < typ.NumField(); i++ {
		f := typ.Field(i)
		key := strings.ToLower(f.Name)
		if tag, ok := f.Tag.Lookup("json"); ok {
			name := strings.Split(tag, ",")[0]
			if name == "-" {
				continue
			}
			if name != "" {
				key = name
			}
		}
		keys = append(keys, key)
	}
	if len(keys) == 0 {
		t.Fatal("GrammarAltSpec reflected to zero fields")
	}
	return keys
}

func TestGrammarSchemaAltKeysMatchGrammarAltSpec(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "schema", "grammar.schema.json"))
	if err != nil {
		t.Fatalf("cannot read schema/grammar.schema.json, so the alt-key "+
			"drift gate cannot run: %v", err)
	}
	var schema map[string]any
	if err := json.Unmarshal(raw, &schema); err != nil {
		t.Fatalf("schema/grammar.schema.json is not valid JSON: %v", err)
	}

	defs, ok := schema["$defs"].(map[string]any)
	if !ok {
		t.Fatal("grammar.schema.json has no $defs object")
	}
	alt, ok := defs["alt"].(map[string]any)
	if !ok {
		t.Fatal("grammar.schema.json has no $defs.alt object " +
			"(ts/test/schema.test.js reads the same path)")
	}
	props, ok := alt["properties"].(map[string]any)
	if !ok {
		t.Fatal("grammar.schema.json $defs.alt has no properties object")
	}
	if ap, ok := alt["additionalProperties"].(bool); !ok || ap {
		t.Error("$defs.alt.additionalProperties must be false: the schema " +
			"must reject unknown alt keys")
	}

	schemaKeys := make([]string, 0, len(props))
	for k := range props {
		schemaKeys = append(schemaKeys, k)
	}
	sort.Strings(schemaKeys)

	structKeys := goAltKeys(t)
	sort.Strings(structKeys)

	if !reflect.DeepEqual(schemaKeys, structKeys) {
		t.Errorf("alt-key drift between schema/grammar.schema.json and Go "+
			"GrammarAltSpec (go/grammarspec.go):\n  schema: %v\n  struct: %v\n"+
			"Update the schema, the Go struct (and mapToGrammarAltSpec), and "+
			"the TS side (ts/src/types.ts GrammarAltSpec, ts/test/schema.test.js "+
			"ALT_KEYS) together.", schemaKeys, structKeys)
	}
}

// registryEntry is one code's record in schema/error-codes.json. The
// optional $comment annotation on an entry is ignored by design.
type registryEntry struct {
	Message string `json:"message"`
	Hint    string `json:"hint"`
}

func TestErrorCodeRegistryMatchesGoCatalogues(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "schema", "error-codes.json"))
	if err != nil {
		t.Fatalf("cannot read schema/error-codes.json, so the registry "+
			"drift gate cannot run: %v", err)
	}
	var reg struct {
		Version string                   `json:"version"`
		Codes   map[string]registryEntry `json:"codes"`
		GoOnly  map[string]registryEntry `json:"goOnly"`
	}
	if err := json.Unmarshal(raw, &reg); err != nil {
		t.Fatalf("schema/error-codes.json is not valid JSON: %v", err)
	}
	if len(reg.Codes) == 0 {
		t.Fatal("schema/error-codes.json declares no codes")
	}

	// The registry is generated from the engine, so its version is the
	// engine version (VERSION here equals ts package.json "version", per
	// version_test.go). A mismatch means the registry was generated by a
	// different engine build than the one under test.
	if reg.Version != VERSION {
		t.Errorf("registry version %q != engine VERSION %q: regenerate with "+
			"cd ts && npm run gen-registry", reg.Version, VERSION)
	}

	// Go's merged catalogues from a default instance, the same access the
	// TS generator uses (a default `new Tabnas()`): Make() copies the
	// package defaults into the parser config (go/parser.go NewParser /
	// go/options.go buildConfig), and the Parser fields alias those maps.
	j := Make()
	msgs := j.parser.ErrorMessages
	hints := j.parser.Hints

	// Direction 1: every registry entry matches Go's catalogue,
	// byte-for-byte. The `internal` entry under goOnly is held to the
	// same bar — it is a literal in ts/tools/gen-error-codes.js, and this
	// is the test that keeps that literal honest.
	check := func(section string, entries map[string]registryEntry) {
		for code, entry := range entries {
			msg, ok := msgs[code]
			if !ok {
				t.Errorf("%s[%q] is in the registry but not in Go's "+
					"errorMessages (go/tabnas.go)", section, code)
				continue
			}
			if msg != entry.Message {
				t.Errorf("%s[%q] message drift:\n  registry: %q\n  go:       %q",
					section, code, entry.Message, msg)
			}
			hint, ok := hints[code]
			if !ok {
				t.Errorf("%s[%q] is in the registry but not in Go's "+
					"defaultHints (go/tabnas.go)", section, code)
				continue
			}
			if hint != entry.Hint {
				t.Errorf("%s[%q] hint drift:\n  registry: %q\n  go:       %q",
					section, code, entry.Hint, hint)
			}
		}
	}
	check("codes", reg.Codes)
	check("goOnly", reg.GoOnly)

	// A code must live in exactly one section.
	for code := range reg.GoOnly {
		if _, dup := reg.Codes[code]; dup {
			t.Errorf("code %q appears in both codes and goOnly", code)
		}
	}

	// Direction 2: every Go catalogue entry appears in the registry —
	// base codes under codes, Go-only ones (i.e. `internal`) under goOnly.
	inRegistry := func(code string) bool {
		_, inCodes := reg.Codes[code]
		_, inGoOnly := reg.GoOnly[code]
		return inCodes || inGoOnly
	}
	for code := range msgs {
		if !inRegistry(code) {
			t.Errorf("Go errorMessages[%q] (go/tabnas.go) is missing from "+
				"schema/error-codes.json: regenerate with cd ts && npm run "+
				"gen-registry (and update the goOnly literal in "+
				"ts/tools/gen-error-codes.js if the code is Go-only)", code)
		}
	}
	for code := range hints {
		if !inRegistry(code) {
			t.Errorf("Go defaultHints[%q] (go/tabnas.go) is missing from "+
				"schema/error-codes.json: regenerate with cd ts && npm run "+
				"gen-registry (and update the goOnly literal in "+
				"ts/tools/gen-error-codes.js if the code is Go-only)", code)
		}
	}
}

// The registry pins the "unknown" hint's {details} placeholder, so the Go
// engine must actually render it — a template the renderer leaves as raw
// "{details}" would make the pinned text dishonest. The bag renders like
// TS strinject: JSON with quotes stripped ({a:one,b:2}); Go sorts the
// keys where TS keeps insertion order (and TS folds a `state` key into
// its bad-token details), which are recorded non-contractual text
// differences (DIVERGENCE.md "Not divergences": error message text).
func TestUnknownHintRendersDetails(t *testing.T) {
	je := makeTabnasError("unknown", "x", "x", 0, 1, 1, nil,
		map[string]any{"b": 2, "a": "one"})
	want := "Unknown error code: unknown\nDetails:\n{a:one,b:2}"
	if je.Hint != want {
		t.Errorf("unknown hint did not render details:\n  got:  %q\n  want: %q",
			je.Hint, want)
	}

	// No details at all still renders, as {} — matching TS, where the
	// details parameter defaults to an empty object.
	je = makeTabnasError("unknown", "x", "x", 0, 1, 1, nil)
	want = "Unknown error code: unknown\nDetails:\n{}"
	if je.Hint != want {
		t.Errorf("empty details did not render as {}:\n  got:  %q\n  want: %q",
			je.Hint, want)
	}
}

// raisingParser builds a minimal grammar whose open alternate raises a bad
// token carrying the given code and details from an alt error fn — the
// public-API funnel every grammar-raised error travels (alt.E → ctx.ParseErr
// → Parser.makeError), as opposed to calling makeTabnasError directly.
func raisingParser(t *testing.T, code string, use map[string]any) *Tabnas {
	t.Helper()
	j := Make(Options{Rule: &RuleOptions{Start: "top"}})
	j.Rule("top", func(rs *RuleSpec, _ *Parser) {
		rs.AddOpen(&AltSpec{S: [][]Tin{{TinNR}},
			E: func(r *Rule, ctx *Context) *Token {
				return ctx.T0.Bad(code, use)
			}})
		rs.AddClose(&AltSpec{S: [][]Tin{{TinZZ}}})
	})
	return j
}

// The {details} wire-up must survive the REAL parse path: Parser.makeError
// re-renders the hint after makeTabnasError, and its re-render bag used to
// lack "details", shipping the raw placeholder for every error raised
// through j.Parse even though the direct makeTabnasError path rendered it.
// TS, same input: "Unknown error code: unknown\nDetails:\n{reason:boom,state:open}"
// (key order and the TS-only `state` detail are non-contractual text).
func TestUnknownHintRendersDetailsThroughParse(t *testing.T) {
	j := raisingParser(t, "unknown", map[string]any{"reason": "boom"})
	_, err := j.Parse("42")
	if err == nil {
		t.Fatal("expected a parse error")
	}
	je, ok := err.(*TabnasError)
	if !ok {
		t.Fatalf("expected *TabnasError, got %T (%v)", err, err)
	}
	want := "Unknown error code: unknown\nDetails:\n{reason:boom}"
	if je.Hint != want {
		t.Errorf("hint through j.Parse did not render details:\n  got:  %q\n  want: %q",
			je.Hint, want)
	}
	if strings.Contains(je.Hint, "{details}") {
		t.Errorf("raw {details} placeholder reached the user: %q", je.Hint)
	}
}

// A code with no hint of its own falls back to the "unknown" hint, with
// the details rendered — TS behavior (ts/src/error.ts errdesc:
// cfg.hint[code] || ... || cfg.hint.unknown). Go used to attach no hint
// at all on a catalogue miss. The TS half of this pair lives in
// ts/test/serialized-grammar.test.js (same raise, same assertions on the
// contractual parts: code preserved, unknown hint text, details rendered).
func TestUncataloguedCodeGetsUnknownHintThroughParse(t *testing.T) {
	j := raisingParser(t, "mystery_code", map[string]any{"what": "it"})
	_, err := j.Parse("42")
	if err == nil {
		t.Fatal("expected a parse error")
	}
	je, ok := err.(*TabnasError)
	if !ok {
		t.Fatalf("expected *TabnasError, got %T (%v)", err, err)
	}
	if je.Code != "mystery_code" {
		t.Errorf("code must be preserved, got %q", je.Code)
	}
	if want := "unknown error: mystery_code"; je.Detail != want {
		t.Errorf("message: got %q, want %q", je.Detail, want)
	}
	want := "Unknown error code: mystery_code\nDetails:\n{what:it}"
	if je.Hint != want {
		t.Errorf("uncatalogued code hint:\n  got:  %q\n  want: %q",
			je.Hint, want)
	}
}
